### ISSUE TITLE
Illegal moves

### ISSUE THREAD

**Issue by CPagador** [tiago-daniel/Talento#2]
Hi,

I see that Talento loses many games by illegal moves. I am attaching a pgn with some examples.

https://www.mediafire.com/file/wb69fj9vvpwceoo/kept+games_(score_margin_reached).pgn/file

Regards,
Carlos

**Comment by tiago-daniel** [comment]
Thank you so much for contributing my using your time to test my engine, that is greatly appreciated and I will make sure to check that out later today.

Regards,
Tiago Daniel

**Comment by tiago-daniel** [comment]
I think the issue was solved on the latest release v0.1.2, there's a binary file for linux and for windows or you can also compile it by yourself with cmake, I'll leave this issue open awaiting for feedback, thank you once again.

**Comment by CPagador** [comment]
> I think the issue was solved on the latest release v0.1.2, there's a binary file for linux and for windows or you can also compile it by yourself with cmake, I'll leave this issue open awaiting for feedback, thank you once again.

Unfortunately, there are more games with illegal moves.

https://www.mediafire.com/file/qnhpda1q7d2p1a2/Talento_0.1.2.pgn/file

**Comment by tiago-daniel** [comment]
Thank you for your reply, that's interesting, it always happens after enemy promoting to queen so I assumed it was related to that and I was right and found a bug where it would not read the promotion right but fixed it, I'm going to investigate further.

**Comment by tiago-daniel** [comment]
I've reuploaded the binary files in the 0.1.2 release, sorry to bother you but can you check with those ? The issue should be fixed, I'll search for other bugs that might cause that problem tho. I've tested with the positions on the last PGN and couldn't replicate the illegal moves anymore yet they were there on the older version, maybe it's the compiled binary that is outdated ? Although I made sure to compile it before upload it. Anyway, if you could check it would be awesome so I could close this issue.

**Comment by CPagador** [comment]
Problem persist:

https://www.mediafire.com/file/4fw9rhm19vb2r63/Talento0.12fix.pgn/file

**Comment by tiago-daniel** [comment]
Weird, I can't find the root of this issue, and when testing locally my new engine doesn't make any more errors, if you send the engine the command uci does it print out 0.1 or 0.1.2 ? if it prints 0.1 can you download the files from the latest 0.1.2 release on this github and check uci command and if it still makes illegal moves ? thanks and sorry for your time, I am trying hard to find the root of this issue

**Comment by CPagador** [comment]
> Weird, I can't find the root of this issue, and when testing locally my new engine doesn't make any more errors, if you send the engine the command uci does it print out 0.1 or 0.1.2 ? if it prints 0.1 can you download the files from the latest 0.1.2 release on this github and check uci command and if it still makes illegal moves ? thanks and sorry for your time, I am trying hard to find the root of this issue

I compared the binaries with WinMerge and also with MD5sum and all of them are different. Anyway, I redownloaded the latest 0.1.2 version and it shows that version when using the uci command also the size of the file is different from the others, but it keeps doing illegal moves.

https://www.mediafire.com/file/mvt8jhk35ngjp6w/Talento012f_im.pgn/file

**Comment by tiago-daniel** [comment]
Alright, I'm continuing to try to find the issue, if possible could you tell me where can I get a copy of another engine and opening books if you used some to try to replicate it myself ? Thanks

**Comment by CPagador** [comment]
You can find many engines here:

https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM/edit?pli=1&gid=175552346#gid=175552346

I use Winboard 4.6.2 GUI, with a common polyglot book for every engine, except for few of them who do not accept external books.

**Comment by tiago-daniel** [comment]
I really can't replicate or find the root of this issue, I'll continue the development normally since I've lost quite a bit of time with this but leave the issue open in case it starts to aggravate or become more discussed, thank you so much for your time and effort put into this, I hope I can impress you in the future with my engine.

**Comment by CPagador** [comment]
New test, this time with CuteChess, meaning a reliable GUI with native compatibility for UCI engines. The illegal moves keep appearing.

https://www.mediafire.com/file/kenz5qodwk5a0jy/Talento2.pgn/file

I will include the latest version of Talento in the next edition of my tournament, because most of these games lost by illegal moves, were hopeless for Talento.

https://talkchess.com/viewtopic.php?t=84433

The tournament will start in some days, I hope you can fix this bug by that time, anyway.

**Comment by tiago-daniel** [comment]
I am focusing today on getting a better search and I am continuously testing my engine to check for any errors, thank you for everything Carlos, I'll try to get my engine better these days.

Tiago

**Comment by rwbc** [comment]
Hi again I was the one who first reported the various illegal moves for Talento, the mate problems and the stalemate problems...
(testing computer chess programs for over 20 years and having been a professional software tester
and ex-programmer)

I played again 400 games with it (newer version before the release just right now) and again I had around 100! illegal
moves vs. Monchester in a quick test, but I had no debug/log files, because I played in the CuteChess GUI w/o setting
up sth for logging. (CuteChess GUI does not by itself unlike CuteChessCli.)

I thought it might be easy for you to replicate most of the serious bugs from the games, but it seems I was wrong.
There are only to valid reasons why you would not have been able to verify and fix those bugs:

1. Talento behaves different in WIN
2. you just fed a position instead of the game history (which is plain wrong of course)

Because of this I let it run with some logger tool now (just 40 games were more than enough) and the logs clearly say that Talento sometimes promotes to a pawn and still very often neglects a promoted Q from the opponent!

I could also verify for the first example that it behaves the same way when fed those given commands from cmd:
(version before new release right now - 1 hour ago)

```
uci
id name Talento 0.1.2
id author Tiago Daniel
uciok
isready
readyok
position startpos moves d2d4 c7c5 d4d5 d7d6 b1c3 g7g6 e2e4 d8a5 f1b5 e8d8 c1e3 f8g7 g1f3 g7c3 b2c3 c8g4 d1d3 a7a6 b5c4 b7b5 f3g5 g8h6 c4b3 f7f6 g5e6 g4e6 d5e6 c5c4 b3c4 b5c4 d3c4 h6g4 e3d4 a5b5 c4b5 a6b5 h2h3 g4h6 d4e3 h6g8 e1g1 a8a4 e3b6 d8c8 f1e1 c8b7 b6d4 a4c4 a1b1 b7a6 b1b4 c4b4 c3b4 b8c6 e1d1 c6b4 d1c1 b4c6 c1d1 c6d8 d4e3 d8e6 d1b1 f6f5 e4f5 g6f5 g2g3 g8f6 b1b3 h8c8 b3a3 a6b7 a3a7 b7c6 a7e7 c8e8 e7e8 f6e8 a2a3 e8f6 g1g2 c6d5 g2f3 f6e4 g3g4 d5e5 f3g2 f5g4 h3g4 e4f6 g2f3 e5d5 g4g5 f6e4 f3g4 e4c3 g4f5 c3b1 a3a4 b1a3 a4b5 a3c2 f5f6 c2a3 b5b6 e6d8 f6e7 d8c6 e7f6 a3c4 b6b7 d5e4 e3c1 e4f3 g5g6 h7g6 f6g6 f3f2 c1g5 c4a5
go wtime 2673 btime 5086 winc 200 binc 200
info depth 1 nodes 20 nps 1428571 score cp 186
info depth 2 nodes 358 nps 5593750 score cp -91
info depth 3 nodes 6357 nps 2023584 score cp 168
info depth 4 nodes 41990 nps -66713 score cp -304
bestmove b7b8p
```

**derived from this logged test game:**

```
[Event "LogTest"]
[Site "RWBC-ESPRESSO Win11Pro Ryzen7 5700G 3.8Ghz 32GB"]
[Date "2024.11.26"]
[Round "8.1.2"]
[White "Talento_012i-64"]
[Black "Monchester_10126-64"]
[Result "0-1"]
[ECO "A43"]
[GameDuration "00:00:45"]
[GameEndTime "2024-11-26T20:12:42.238 Mitteleuropäische Zeit"]
[GameStartTime "2024-11-26T20:11:56.439 Mitteleuropäische Zeit"]
[Opening "Old Benoni"]
[PlyCount "120"]
[Termination "illegal move"]
[TimeControl "15+0.2"]
[Variation "Schmid's system"]

1. d4 {book} c5 {book}
2. d5 {book} d6 {book}
3. Nc3 {book} g6 {book}
4. e4 {+0.06/4 0.86} Qa5 {+7.74/5 1.66}
5. Bb5+ {-1.48/4 0.83} Kd8 {+8.05/5 0.33}
6. Be3 {-1.41/4 0.80} Bg7 {+9.05/5 2.87}
7. Nf3 {-1.48/4 0.77} Bxc3+ {+9.00/4 0.17}
8. bxc3 {-3.20/4 0.74} Bg4 {+11.00/5 2.31}
9. Qd3 {-1.66/4 0.71} a6 {+3.02/4 0.13}
10. Bc4 {-0.93/4 0.69} b5 {+2.97/4 0.11}
11. Ng5 {-0.86/4 1.20} Nh6 {+0.80/4 0.086}
12. Bb3 {-0.82/4 0.61} f6 {+0.60/4 0.10}
13. Ne6+ {+1.06/4 0.59} Bxe6 {+8.42/5 0.28}
14. dxe6 {-0.18/4 0.57} c4 {+10.68/5 1.21}
15. Bxc4 {-0.27/4 0.55} bxc4 {+10.45/5 1.24}
16. Qxc4 {-0.82/4 0.53} Ng4 {+10.48/5 1.67}
17. Bd4 {-0.78/4 0.52} Qb5 {+8.51/4 0.088}
18. Qxb5 {-0.15/4 0.50} axb5 {+9.54/5 0.76}
19. h3 {-0.53/4 0.49} Nh6 {+9.51/5 0.63}
20. Be3 {+0.29/4 0.47} Ng8 {+9.94/5 0.57}
21. O-O {-0.24/4 0.46} Ra4 {+10.11/5 0.30}
22. Bb6+ {-0.31/4 0.45} Kc8 {+10.60/5 0.029}
23. Rfe1 {-0.65/4 0.43} Kb7 {+10.77/5 0.36}
24. Bd4 {-0.88/4 0.42} Rc4 {+10.71/5 0.47}
25. Rab1 {-0.52/4 0.41} Ka6 {+9.97/5 0.52}
26. Rb4 {-0.08/4 0.40} Rxb4 {+10.08/5 0.30}
27. cxb4 {-0.45/4 0.39} Nc6 {+10.14/5 0.073}
28. Rd1 {-0.87/4 0.38} Nxb4 {+11.71/5 0.14}
29. Rc1 {-1.14/4 0.37} Nc6 {+11.08/5 0.14}
30. Rd1 {-1.83/4 0.36} Nd8 {+11.77/5 0.19}
31. Be3 {-2.13/4 0.35} Nxe6 {+11.82/5 0.16}
32. Rb1 {-2.29/4 0.35} f5 {+11.88/5 0.25}
33. exf5 {-2.30/4 0.34} gxf5 {+11.88/5 0.32}
34. g3 {-2.57/4 0.33} Nf6 {+12.02/5 0.24}
35. Rb3 {-2.90/4 0.33} Rc8 {+11.11/4 0.041}
36. Ra3+ {-2.65/4 0.32} Kb7 {+11.34/1 0}
37. Ra7+ {-2.63/4 0.31} Kc6 {+11.28/5 0.065}
38. Rxe7 {-2.68/4 0.31} Re8 {+9.68/4 0.047}
39. Rxe8 {-1.68/4 0.30} Nxe8 {+10.94/5 0.51}
40. a3 {-1.99/4 0.30} Nf6 {+11.31/5 0.16}
41. Kg2 {-2.50/4 0.29} Kd5 {+11.22/5 0.28}
42. Kf3 {-2.55/4 0.29} Ne4 {+11.37/5 0.14}
43. g4 {-1.81/5 0.28} Ke5 {+11.17/5 0.18}
44. Kg2 {-1.92/5 0.28} fxg4 {+11.25/5 0.25}
45. hxg4 {-2.74/4 0.28} Nf6 {+11.20/5 0.19}
46. Kf3 {-2.59/4 0.27} Kd5 {+11.25/5 0.11}
47. g5 {-1.31/5 0.27} Ne4 {+11.60/5 0.13}
48. Kg4 {-1.21/5 0.27} Nc3 {+11.31/5 0.15}
49. Kf5 {-2.65/4 0.26} Nb1 {+11.45/5 0.096}
50. a4 {-0.84/5 0.26} Na3 {+11.54/5 0.096}
51. axb5 {-0.70/5 0.26} Nxc2 {+11.17/5 0.064}
52. Kf6 {-0.69/5 0.25} Na3 {+11.74/5 0.094}
53. b6 {+0.17/5 0.25} Nd8 {+11.08/5 0.084}
54. Ke7 {+0.34/5 0.25} Nc6+ {+11.22/5 0.055}
55. Kf6 {+0.28/5 0.24} Nc4 {+11.22/5 0.075}
56. b7 {+0.48/5 0.24} Ke4 {+11.22/5 0.14}
57. Bc1 {-1.20/4 0.24} Kf3 {+11.08/5 0.17}
58. g6 {-1.37/4 0.24} hxg6 {+11.94/5 0.27}
59. Kxg6 {-2.23/4 0.24} Kxf2 {+12.00/5 0.17}
60. Bg5 {-1.38/4 0.23} N4a5 {+12.20/5 0.28}
{White makes an illegal move: b7b8p}
0-1
```
**log snippet**

```
794.922: < bestmove c1g5
795.187: > position startpos moves d2d4 c7c5 d4d5 d7d6 b1c3 g7g6 e2e4 d8a5 f1b5 e8d8 c1e3 f8g7 g1f3 g7c3 b2c3 c8g4 d1d3 a7a6 b5c4 b7b5 f3g5 g8h6 c4b3 f7f6 g5e6 g4e6 d5e6 c5c4 b3c4 b5c4 d3c4 h6g4 e3d4 a5b5 c4b5 a6b5 h2h3 g4h6 d4e3 h6g8 e1g1 a8a4 e3b6 d8c8 f1e1 c8b7 b6d4 a4c4 a1b1 b7a6 b1b4 c4b4 c3b4 b8c6 e1d1 c6b4 d1c1 b4c6 c1d1 c6d8 d4e3 d8e6 d1b1 f6f5 e4f5 g6f5 g2g3 g8f6 b1b3 h8c8 b3a3 a6b7 a3a7 b7c6 a7e7 c8e8 e7e8 f6e8 a2a3 e8f6 g1g2 c6d5 g2f3 f6e4 g3g4 d5e5 f3g2 f5g4 h3g4 e4f6 g2f3 e5d5 g4g5 f6e4 f3g4 e4c3 g4f5 c3b1 a3a4 b1a3 a4b5 a3c2 f5f6 c2a3 b5b6 e6d8 f6e7 d8c6 e7f6 a3c4 b6b7 d5e4 e3c1 e4f3 g5g6 h7g6 f6g6 f3f2 c1g5 c4a5
795.187: > isready
795.187: < readyok
795.187: > go wtime 2673 btime 5086 winc 200 binc 200
795.187: < info depth 1 nodes 20 nps 1538461 score cp 186
795.187: < info depth 2 nodes 358 nps 2265822 score cp -91
795.203: < info depth 3 nodes 6357 nps 1223758 score cp 168
795.219: < info depth 4 nodes 41990 nps -60954 score cp -304
795.422: < bestmove b7b8p
```

more later after my late meal...

Guenther
(RWBC + maintainer of the XB/UCI chronology)

and BTW this is the behaviour of the now released Talento 0.2.0 (which still reports 0.1.2)
(will check the other illegal moves later with that version too)
```
uci
id name Talento 0.1.2
id author Tiago Daniel
uciok
isready
readyok
position startpos moves d2d4 c7c5 d4d5 d7d6 b1c3 g7g6 e2e4 d8a5 f1b5 e8d8 c1e3 f8g7 g1f3 g7c3 b2c3 c8g4 d1d3 a7a6 b5c4 b7b5 f3g5 g8h6 c4b3 f7f6 g5e6 g4e6 d5e6 c5c4 b3c4 b5c4 d3c4 h6g4 e3d4 a5b5 c4b5 a6b5 h2h3 g4h6 d4e3 h6g8 e1g1 a8a4 e3b6 d8c8 f1e1 c8b7 b6d4 a4c4 a1b1 b7a6 b1b4 c4b4 c3b4 b8c6 e1d1 c6b4 d1c1 b4c6 c1d1 c6d8 d4e3 d8e6 d1b1 f6f5 e4f5 g6f5 g2g3 g8f6 b1b3 h8c8 b3a3 a6b7 a3a7 b7c6 a7e7 c8e8 e7e8 f6e8 a2a3 e8f6 g1g2 c6d5 g2f3 f6e4 g3g4 d5e5 f3g2 f5g4 h3g4 e4f6 g2f3 e5d5 g4g5 f6e4 f3g4 e4c3 g4f5 c3b1 a3a4 b1a3 a4b5 a3c2 f5f6 c2a3 b5b6 e6d8 f6e7 d8c6 e7f6 a3c4 b6b7 d5e4 e3c1 e4f3 g5g6 h7g6 f6g6 f3f2 c1g5 c4a5
go wtime 2673 btime 5086 winc 200 binc 200
info depth 1 nodes 39 nps 93975 score cp -84
info depth 2 nodes 80 nps 271186 score cp -91
info depth 3 nodes 540 nps 423197 score cp -278
info depth 4 nodes 2800 nps -217449 score cp -304
info depth 5 nodes 15875 nps -41824 score cp -285
bestmove b7b8r
```

**Comment by tiago-daniel** [comment]
Hello @rwbc and thanks again, I remember talking with you in the discord, I thought the root of the problem was on my engine interpreting the moves in a wrong way but that apparently wasn't the the root of this issue since it still happens, I also tried testing it with giving the engine the history of moves and not the position and I can see why just giving the position is wrong as it would not have the need to play the moves itself, now with those logs I will try to test it, I never tested the engine on Windows tho but I will try it, thank you so much for your help and I hope to close this issue for once.

**Comment by rwbc** [comment]
```
[Event "LogTest"]
[Site "RWBC-ESPRESSO Win11Pro Ryzen7 5700G 3.8Ghz 32GB"]
[Date "2024.11.26"]
[Round "2.1.1"]
[White "Monchester_10126-64"]
[Black "Talento_012i-64"]
[Result "1-0"]
[ECO "A06"]
[GameDuration "00:00:47"]
[GameEndTime "2024-11-26T20:02:01.588 Mitteleuropäische Zeit"]
[GameStartTime "2024-11-26T20:01:14.092 Mitteleuropäische Zeit"]
[Opening "Reti"]
[PlyCount "125"]
[Termination "illegal move"]
[TimeControl "15+0.2"]
[Variation "Nimzowitsch-Larsen attack"]

1. Nf3 {book} d5 {book}
2. b3 {book} Bg4 {book}
3. d4 {book} e6 {book}
4. Ne5 {+0.82/5 2.29} Nf6 {-1.41/4 0.86}
5. Qd3 {-0.57/4 0.065} Bf5 {-0.69/4 0.83}
6. Qb5+ {-0.34/4 0.098} c6 {-0.41/4 0.80}
7. Qxb7 {-0.11/4 0.10} Nbd7 {-4.18/4 0.77}
8. Nxc6 {+2.02/4 0.11} Qc8 {-1.53/4 0.74}
9. Qxc8+ {+1.80/4 0.091} Rxc8 {+0.95/5 0.71}
10. Nxa7 {+2.25/5 2.52} Rxc2 {-0.49/4 0.84}
11. Bg5 {+2.22/5 1.29} Ne4 {-0.13/4 0.65}
12. Be3 {+2.17/5 1.43} Bb4+ {-0.19/4 0.63}
13. Kd1 {+2.22/5 0.20} Nef6 {-0.19/4 0.61}
14. Bg5 {+2.22/5 1.09} Ng4 {+0.31/4 0.59}
15. Be3 {+1.71/5 1.55} O-O {+0.47/4 0.57}
16. h3 {+2.34/5 0.92} Nxe3+ {+0.43/4 0.55}
17. fxe3 {+3.68/1 0} Nf6 {+0.30/4 0.53}
18. a3 {+3.65/5 0.34} Bd6 {+0.25/4 0.52}
19. Nb5 {+4.34/5 0.46} Bg3 {-0.86/4 0.50}
20. N1c3 {+4.14/5 0.33} Rb2 {-0.51/4 0.48}
21. b4 {+4.08/5 0.53} Bf2 {-0.65/4 0.47}
22. Na4 {+4.14/5 0.48} Rc2 {-0.64/4 0.46}
23. g4 {+4.20/5 0.45} Bg6 {-0.10/4 0.45}
24. g5 {+4.11/5 0.42} Nd7 {-0.32/4 0.43}
25. e4 {+3.28/5 0.42} Bxe4 {-0.09/4 0.42}
26. Bg2 {+3.14/5 0.58} Rc4 {-0.04/4 0.41}
27. Bxe4 {+3.74/5 1.03} dxe4 {-0.99/4 0.40}
28. Ra2 {+3.14/5 0.63} Rfc8 {+0.30/4 0.39}
29. Nac3 {+3.48/5 0.82} Rxc3 {+0.68/4 0.38}
30. Nxc3 {+8.45/5 0.68} Rxc3 {+0.71/4 0.37}
31. Rf1 {+8.91/5 0.30} Be3 {+0.31/4 0.36}
32. Rc2 {+8.88/5 0.39} Rxc2 {-0.37/4 0.35}
33. Kxc2 {+8.54/5 0.21} Bxg5 {-0.23/4 0.35}
34. Kb3 {+7.25/4 0.013} Bh6 {0.00/4 0.34}
35. Rb1 {+7.28/4 0.009} Be3 {+0.62/4 0.33}
36. Rf1 {+8.28/5 0.22} Nb6 {+0.59/4 0.33}
37. Rd1 {+8.14/5 0.27} h5 {+0.76/4 0.32}
38. a4 {+8.17/5 0.19} h4 {+0.51/4 0.31}
39. a5 {+8.14/5 0.17} Nd5 {-0.25/4 0.31}
40. a6 {+8.31/5 0.18} Nc7 {-1.18/4 0.30}
41. a7 {+8.31/5 0.21} Na8 {-1.67/4 0.30}
42. Kc2 {+8.31/5 0.15} e5 {+0.19/5 0.29}
43. dxe5 {+9.60/5 0.13} Bxa7 {-2.32/4 0.29}
44. Rd8+ {+17.17/4 0.009} Kh7 {-1.32/5 0.28}
45. Rxa8 {+16.94/4 0.009} Bd4 {-1.10/5 0.28}
46. Rf8 {+17.05/4 0.008} Kg6 {-1.08/5 0.28}
47. Re8 {+18.17/5 0.13} Kf5 {-1.10/5 0.27}
48. Re7 {+18.25/5 0.14} Bxe5 {-1.28/5 0.27}
49. Rxf7+ {+18.02/5 0.11} Ke6 {-1.39/5 0.27}
50. Rf8 {+18.20/5 0.16} Ke7 {-2.29/4 0.26}
51. Rh8 {+18.34/5 0.19} e3 {-2.26/4 0.26}
52. Rxh4 {+19.20/5 0.13} Kf6 {-2.67/5 0.26}
53. Kd3 {+19.37/5 0.11} g5 {-2.44/5 0.25}
54. Rg4 {+19.65/5 0.092} Bf4 {-2.98/5 0.25}
55. Ke4 {+19.60/5 0.063} Kg7 {-3.06/5 0.25}
56. h4 {+20.20/5 0.058} Kf6 {-2.68/5 0.24}
57. b5 {+20.25/5 0.050} Kg6 {-3.38/5 0.24}
58. hxg5 {+20.77/5 0.053} Bxg5 {-3.57/5 0.24}
59. b6 {+34.48/5 0.029} Kh5 {-4.36/5 0.24}
60. Rxg5+ {+42.54/5 0.058} Kxg5 {-6.00/7 0.24}
61. b7 {+43.42/5 0.004} Kh4 {-6.26/6 0.23}
62. b8=Q {+44.14/5 0.009} Kg4 {-1.80/7 0.23}
63. Kxe3 {+43.71/4 0.003}
{Black makes an illegal move: g4g3}
1-0
```
**from log for this game**
```
154.547: < bestmove h4g4
154.547: > position startpos moves g1f3 d7d5 b2b3 c8g4 d2d4 e7e6 f3e5 g8f6 d1d3 g4f5 d3b5 c7c6 b5b7 b8d7 e5c6 d8c8 b7c8 a8c8 c6a7 c8c2 c1g5 f6e4 g5e3 f8b4 e1d1 e4f6 e3g5 f6g4 g5e3 e8g8 h2h3 g4e3 f2e3 d7f6 a2a3 b4d6 a7b5 d6g3 b1c3 c2b2 b3b4 g3f2 c3a4 b2c2 g2g4 f5g6 g4g5 f6d7 e3e4 g6e4 f1g2 c2c4 g2e4 d5e4 a1a2 f8c8 a4c3 c4c3 b5c3 c8c3 h1f1 f2e3 a2c2 c3c2 d1c2 e3g5 c2b3 g5h6 f1b1 h6e3 b1f1 d7b6 f1d1 h7h5 a3a4 h5h4 a4a5 b6d5 a5a6 d5c7 a6a7 c7a8 b3c2 e6e5 d4e5 e3a7 d1d8 g8h7 d8a8 a7d4 a8f8 h7g6 f8e8 g6f5 e8e7 d4e5 e7f7 f5e6 f7f8 e6e7 f8h8 e4e3 h8h4 e7f6 c2d3 g7g5 h4g4 e5f4 d3e4 f6g7 h3h4 g7f6 b4b5 f6g6 h4g5 f4g5 b5b6 g6h5 g4g5 h5g5 b6b7 g5h4 b7b8q h4g4 e4e3
154.547: > isready
154.547: < readyok
154.547: > go wtime 4406 btime 2639 winc 200 binc 200
154.547: < info depth 1 nodes 6 nps 1500000 score cp -180
154.547: < info depth 2 nodes 42 nps 3818181 score cp -184
154.547: < info depth 3 nodes 236 nps 4627450 score cp -190
154.547: < info depth 4 nodes 1894 nps 6862318 score cp -196
154.547: < info depth 5 nodes 11916 nps -528876 score cp -178
154.562: < info depth 6 nodes 28262 nps -138738 score cp -184
154.656: < info depth 7 nodes 10789 nps -22157 score cp -184
154.781: < bestmove g4g3
```
**previous version verified the bug**
```
ucinewgame
isready
readyok
position startpos moves g1f3 d7d5 b2b3 c8g4 d2d4 e7e6 f3e5 g8f6 d1d3 g4f5 d3b5 c7c6 b5b7 b8d7 e5c6 d8c8 b7c8 a8c8 c6a7 c8c2 c1g5 f6e4 g5e3 f8b4 e1d1 e4f6 e3g5 f6g4 g5e3 e8g8 h2h3 g4e3 f2e3 d7f6 a2a3 b4d6 a7b5 d6g3 b1c3 c2b2 b3b4 g3f2 c3a4 b2c2 g2g4 f5g6 g4g5 f6d7 e3e4 g6e4 f1g2 c2c4 g2e4 d5e4 a1a2 f8c8 a4c3 c4c3 b5c3 c8c3 h1f1 f2e3 a2c2 c3c2 d1c2 e3g5 c2b3 g5h6 f1b1 h6e3 b1f1 d7b6 f1d1 h7h5 a3a4 h5h4 a4a5 b6d5 a5a6 d5c7 a6a7 c7a8 b3c2 e6e5 d4e5 e3a7 d1d8 g8h7 d8a8 a7d4 a8f8 h7g6 f8e8 g6f5 e8e7 d4e5 e7f7 f5e6 f7f8 e6e7 f8h8 e4e3 h8h4 e7f6 c2d3 g7g5 h4g4 e5f4 d3e4 f6g7 h3h4 g7f6 b4b5 f6g6 h4g5 f4g5 b5b6 g6h5 g4g5 h5g5 b6b7 g5h4 b7b8q h4g4 e4e3
go wtime 4406 btime 2639 winc 200 binc 200
info depth 1 nodes 6 nps 857142 score cp -180
info depth 2 nodes 42 nps 2470588 score cp -184
info depth 3 nodes 236 nps 4452830 score cp -190
info depth 4 nodes 1894 nps 5335211 score cp -196
info depth 5 nodes 11916 nps -499691 score cp -178
info depth 6 nodes 28262 nps -143145 score cp -184
info depth 7 nodes 10789 nps -22693 score cp -184
bestmove g4g3
```

**new version which should be 0.2.0**
(same bug still)
```
ucinewgame
uci
id name Talento 0.1.2
id author Tiago Daniel
uciok
isready
readyok
position startpos moves g1f3 d7d5 b2b3 c8g4 d2d4 e7e6 f3e5 g8f6 d1d3 g4f5 d3b5 c7c6 b5b7 b8d7 e5c6 d8c8 b7c8 a8c8 c6a7 c8c2 c1g5 f6e4 g5e3 f8b4 e1d1 e4f6 e3g5 f6g4 g5e3 e8g8 h2h3 g4e3 f2e3 d7f6 a2a3 b4d6 a7b5 d6g3 b1c3 c2b2 b3b4 g3f2 c3a4 b2c2 g2g4 f5g6 g4g5 f6d7 e3e4 g6e4 f1g2 c2c4 g2e4 d5e4 a1a2 f8c8 a4c3 c4c3 b5c3 c8c3 h1f1 f2e3 a2c2 c3c2 d1c2 e3g5 c2b3 g5h6 f1b1 h6e3 b1f1 d7b6 f1d1 h7h5 a3a4 h5h4 a4a5 b6d5 a5a6 d5c7 a6a7 c7a8 b3c2 e6e5 d4e5 e3a7 d1d8 g8h7 d8a8 a7d4 a8f8 h7g6 f8e8 g6f5 e8e7 d4e5 e7f7 f5e6 f7f8 e6e7 f8h8 e4e3 h8h4 e7f6 c2d3 g7g5 h4g4 e5f4 d3e4 f6g7 h3h4 g7f6 b4b5 f6g6 h4g5 f4g5 b5b6 g6h5 g4g5 h5g5 b6b7 g5h4 b7b8q h4g4 e4e3
go wtime 4406 btime 2639 winc 200 binc 200
info depth 1 nodes 6 nps 77922 score cp -180
info depth 2 nodes 15 nps 272727 score cp -184
info depth 3 nodes 137 nps 919463 score cp -190
info depth 4 nodes 297 nps 455521 score cp -184
info depth 5 nodes 1441 nps 874393 score cp -178
info depth 6 nodes 4891 nps 80317 score cp -184
info depth 7 nodes 24594 nps -32643 score cp -184
info depth 8 nodes 521 nps 3256 score cp -190
bestmove g4g3
```

**Comment by rwbc** [comment]
If you need more of those, check those files attached. (log.pgn and IO.log)

[IO.zip](https://github.com/user-attachments/files/17925693/IO.zip)
[log.zip](https://github.com/user-attachments/files/17925694/log.zip)

**Comment by tiago-daniel** [comment]
I can't replicate it on Linux at least, everytime I try to it plays a legal move, I even changed the code to print all the moves it has and it doesn't even print the illegal ones, so this must be a compilation to Windows error, it might be of a setting I have so I would like to try a new one and ask you to test it. Also the one where it tries to promote to a pawn on my one tries to promote to a queen and if I make him list all moves it doesn't have that possibility.

**Comment by tiago-daniel** [comment]
Ok I managed to get a coding environment on Windows and tested it and it actually behaves differently, it actually plays the ilegal moves on Windows and I am flabbergasted how did this happen, I'm going to try to fix it now that I'm at it.

**Comment by tiago-daniel** [comment]
I think I fixed it ! I'll update v0.2.0 files with the new ones, it was actually only happening on windows but it was an UB I left on my code that linux was handling well but apparently windows was not, when I made that error I thought I was actually preventing it but I put the wrong values in the wrong place, now everything is all right.

**Comment by tiago-daniel** [comment]
When possible, please test it on your windows system to see if everything's alright and we close this issue for good.

**Comment by CPagador** [comment]
> When possible, please test it on your windows system to see if everything's alright and we close this issue for good.

In my last test, I could not find any loss by illegal move from Talento 0.2.0. Great!

**Comment by rwbc** [comment]
I can confirm that there are no illegal moves anymore in a test with 500 games (tc was 15+0.3)!

Also Monchester now is much much too weak for testing Talento against now.

```
Score of Talento_020-64 vs Monchester_10126-64: 481 - 14 - 5 [0.967]
...      Talento_020-64 playing White: 239 - 8 - 3  [0.962] 250
...      Talento_020-64 playing Black: 242 - 6 - 2  [0.972] 250
...      White vs Black: 245 - 250 - 5  [0.495] 500
Elo difference: 586.8 +/- 88.0, LOS: 100.0 %, DrawRatio: 1.0 %
500 of 500 games finished.

Player: Talento_020-64
   "Draw by 3-fold repetition": 4
   "Draw by fifty moves rule": 1
   "Loss: Black mates": 8
   "Loss: White mates": 6
   "Win: Black loses on time": 2
   "Win: Black mates": 236
   "Win: White loses on time": 6
   "Win: White mates": 237
Player: Monchester_10126-64
   "Draw by 3-fold repetition": 4
   "Draw by fifty moves rule": 1
   "Loss: Black loses on time": 2
   "Loss: Black mates": 236
   "Loss: White loses on time": 6
   "Loss: White mates": 237
   "Win: Black mates": 8
   "Win: White mates": 6
```
Two things found though in those 500 games, which might justify a new issue.
